@php
    /**
     * DomPDF constraints applied throughout this template:
     *  - Inline styles only; no external CSS, no @import.
     *  - HEX color literals only; no var(--token).
     *  - 'DejaVu Sans' family for full Indonesian unicode support.
     *  - No flexbox / grid; <table> for any column layout.
     *  - Page breaks via <div style="page-break-before: always;">
     */

    $brandName     = $audit->brand_name ?: '—';
    $generatedAt   = now()->locale('id')->translatedFormat('d F Y H:i');
    $overallScore  = $audit->overall_score;
    $overallLabel  = $audit->overall_label ?: '—';
    $pillarScores  = (array) ($audit->pillar_scores ?? []);
    $subBuckets     = (array) ($audit->sub_bucket_scores ?? []);
    $scoreBreakdown = (array) ($audit->score_breakdown ?? []);
    $findings       = (array) ($audit->key_findings ?? []);
    $recommends    = (array) ($audit->recommendations ?? []);

    // Reverse lookup: bucket slug -> pillar slug, used for grouping recommendations.
    $bucketToPillar = [];
    foreach ($subBuckets as $pillarSlug => $buckets) {
        foreach (array_keys((array) $buckets) as $bucket) {
            $bucketToPillar[$bucket] = $pillarSlug;
        }
    }

    $tierColor = static fn (?int $s): string => match (true) {
        ($s ?? 0) >= 70 => '#3D8948', // chimera-500
        ($s ?? 0) >= 50 => '#C97A1B', // warning
        default         => '#C24E3A', // danger
    };
    $overallColor = $tierColor($overallScore);

    $positiveFindings = array_values(array_filter($findings, fn ($f) => is_array($f) && ($f['impact'] ?? '') === 'positive'));
    $concernFindings  = array_values(array_filter($findings, fn ($f) => is_array($f) && ($f['impact'] ?? '') === 'negative'));
@endphp
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Brand Health Check — {{ $brandName }}</title>
    <style>
        /* DomPDF supports a small subset; keep simple. */
        @page { margin: 36px 32px 56px 32px; }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            line-height: 1.5;
            color: #0F1411;
            margin: 0;
            padding: 0;
            background: #FFFFFF;
        }
        h1, h2, h3, h4 { margin: 0; font-weight: bold; color: #0F1411; }
        p { margin: 0 0 6px 0; }
        table { border-collapse: collapse; width: 100%; }
        td { vertical-align: top; }
        .muted { color: #5A6259; }
        .tertiary { color: #8A9088; }
        .footer-line {
            position: fixed; bottom: -38px; left: 0; right: 0;
            font-size: 8px; color: #8A9088;
            border-top: 1px solid rgba(15,20,17,0.08);
            padding-top: 8px;
        }
        .footer-line .pagenum:before { content: counter(page); }
    </style>
</head>
<body>

{{-- ========================== Page footer (every page) ========================== --}}
<div class="footer-line">
    <table>
        <tr>
            <td style="text-align: left; font-size: 8px; color: #8A9088;">
                Generated by Nema Brand Health Check · {{ $generatedAt }}
            </td>
            <td style="text-align: right; font-size: 8px; color: #8A9088;">
                Halaman <span class="pagenum"></span>
            </td>
        </tr>
    </table>
</div>

{{-- ========================== HEADER ========================== --}}
<table style="border-bottom: 2px solid #3D8948; padding-bottom: 12px; margin-bottom: 24px;">
    <tr>
        <td style="width: 60%;">
            <table>
                <tr>
                    <td style="width: 36px; vertical-align: middle;">
                        {{-- Inline SVG logo (leaf in a green circle) --}}
                        <svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="16" cy="16" r="16" fill="#3D8948"/>
                            <path d="M9 22 C 12 12, 22 10, 23 9 C 22 18, 18 22, 9 22 Z" fill="#FFFFFF"/>
                            <path d="M9 22 L 16 14" stroke="#3D8948" stroke-width="1.4" fill="none"/>
                        </svg>
                    </td>
                    <td style="vertical-align: middle; padding-left: 8px;">
                        <p style="font-size: 14px; font-weight: bold; color: #3D8948; margin: 0;">Nema</p>
                        <p style="font-size: 9px; color: #5A6259; margin: 0;">Brand Health Check Report</p>
                    </td>
                </tr>
            </table>
        </td>
        <td style="width: 40%; text-align: right;">
            <p style="font-size: 16px; font-weight: bold; color: #0F1411; margin: 0;">{{ $brandName }}</p>
            <p style="font-size: 9px; color: #8A9088; margin: 2px 0 0 0;">Diterbitkan {{ $generatedAt }}</p>
        </td>
    </tr>
</table>

{{-- ========================== OVERALL SCORE ========================== --}}
<div style="background: #F0F4EE; border: 1px solid rgba(15,20,17,0.08); border-radius: 12px; padding: 24px; margin-bottom: 24px;">
    <table>
        <tr>
            <td style="width: 30%; text-align: center; vertical-align: middle;">
                <div style="display: inline-block; width: 120px; height: 120px; border: 8px solid {{ $overallColor }}; border-radius: 60px; text-align: center; padding-top: 28px; box-sizing: border-box;">
                    <p style="font-size: 36px; font-weight: bold; color: {{ $overallColor }}; margin: 0; line-height: 1;">{{ $overallScore ?? '—' }}</p>
                    <p style="font-size: 9px; color: #8A9088; margin: 2px 0 0 0;">dari 100</p>
                </div>
            </td>
            <td style="width: 70%; vertical-align: middle; padding-left: 24px;">
                <p style="font-size: 9px; color: #8A9088; margin: 0;">Skor Keseluruhan</p>
                <p style="font-size: 18px; font-weight: bold; color: #0F1411; margin: 4px 0 12px 0;">{{ $overallLabel }}</p>
                <p style="font-size: 11px; color: #5A6259; line-height: 1.55; margin: 0;">
                    @php
                        $tierDesc = match (true) {
                            ($overallScore ?? 0) >= 80 => 'Brand Anda sudah sangat kuat. Fokus pada area terkecil untuk mempertahankan posisi premium.',
                            ($overallScore ?? 0) >= 70 => 'Brand Anda di posisi baik dengan potensi tinggi. Beberapa area perlu penguatan untuk mencapai tier teratas.',
                            ($overallScore ?? 0) >= 50 => 'Brand Anda memiliki fondasi yang baik namun beberapa pilar membutuhkan perhatian.',
                            default                    => 'Brand Anda memiliki banyak ruang untuk berkembang. Mulai dari rekomendasi prioritas tinggi.',
                        };
                    @endphp
                    {{ $tierDesc }}
                </p>
            </td>
        </tr>
    </table>
</div>

{{-- ========================== KEY FINDINGS (kept on first pages) ========================== --}}
@if (count($positiveFindings) > 0 || count($concernFindings) > 0)
    <h2 style="font-size: 13px; margin-bottom: 8px;">Temuan Utama</h2>
    <table style="margin-bottom: 24px;">
        <tr>
            <td style="width: 50%; vertical-align: top; padding-right: 8px;">
                <p style="font-size: 10px; font-weight: bold; color: #3D8948; margin-bottom: 6px;">Positif</p>
                @forelse ($positiveFindings as $f)
                    <div style="border-left: 3px solid #3D8948; padding: 6px 10px; margin-bottom: 6px; background: #E8F1E5;">
                        <p style="font-size: 9px; color: #0F1411; margin: 0; line-height: 1.55;">{{ $f['observation'] ?? '' }}</p>
                        @if (! empty($f['touchpoint']))
                            <p style="font-size: 8px; color: #8A9088; margin: 2px 0 0 0;">{{ $f['touchpoint'] }}</p>
                        @endif
                    </div>
                @empty
                    <p style="font-size: 9px; color: #8A9088;">—</p>
                @endforelse
            </td>
            <td style="width: 50%; vertical-align: top; padding-left: 8px;">
                <p style="font-size: 10px; font-weight: bold; color: #C97A1B; margin-bottom: 6px;">Perlu Perhatian</p>
                @forelse ($concernFindings as $f)
                    <div style="border-left: 3px solid #C97A1B; padding: 6px 10px; margin-bottom: 6px; background: #FEF3DC;">
                        <p style="font-size: 9px; color: #0F1411; margin: 0; line-height: 1.55;">{{ $f['observation'] ?? '' }}</p>
                        @if (! empty($f['touchpoint']))
                            <p style="font-size: 8px; color: #8A9088; margin: 2px 0 0 0;">{{ $f['touchpoint'] }}</p>
                        @endif
                    </div>
                @empty
                    <p style="font-size: 9px; color: #8A9088;">—</p>
                @endforelse
            </td>
        </tr>
    </table>
@endif

{{-- ========================== PILLAR SECTIONS ========================== --}}
@foreach ($pillarOrder as $loopIdx => $slug)
    @php
        $data         = $pillarScores[$slug] ?? null;
        $pillarScore  = is_array($data) ? ($data['score'] ?? null) : null;
        $pillarColor  = $tierColor($pillarScore);
        $evidence     = is_array($data) ? (array) ($data['evidence'] ?? []) : [];
        $reasoning    = is_array($data) ? (string) ($data['reasoning'] ?? '') : '';
        $bucketScores = (array) ($subBuckets[$slug] ?? []);
        $bdByBucket   = (array) ($scoreBreakdown[$slug] ?? []);
        $pillarLabel  = $pillarLabels[$slug] ?? $slug;
    @endphp

    {{-- Each pillar starts a new page so reasoning + evidence don't get split awkwardly. --}}
    <div style="page-break-before: always;"></div>

    {{-- Pillar header --}}
    <table style="margin-bottom: 12px;">
        <tr>
            <td style="width: 70%;">
                <p style="font-size: 8px; color: #8A9088; margin: 0;">PILAR {{ $loopIdx + 1 }} DARI 4</p>
                <h2 style="font-size: 18px; color: #0F1411; margin: 4px 0 0 0;">{{ $pillarLabel }}</h2>
            </td>
            <td style="width: 30%; text-align: right; vertical-align: middle;">
                <p style="font-size: 32px; font-weight: bold; color: {{ $pillarColor }}; margin: 0; line-height: 1;">{{ $pillarScore ?? '—' }}</p>
                <p style="font-size: 9px; color: #8A9088; margin: 2px 0 0 0;">dari 100</p>
            </td>
        </tr>
    </table>

    {{-- Score bar --}}
    <div style="height: 6px; background: #E8F1E5; border-radius: 3px; margin-bottom: 18px;">
        <div style="height: 6px; background: {{ $pillarColor }}; width: {{ $pillarScore ?? 0 }}%; border-radius: 3px;"></div>
    </div>

    {{-- Sub-bucket breakdown --}}
    @if (count($bucketScores) > 0)
        <h3 style="font-size: 11px; color: #5A6259; margin-bottom: 8px;">Rincian Sub-Bucket</h3>
        <table style="border: 1px solid rgba(15,20,17,0.08); margin-bottom: 18px;">
            @foreach ($bucketScores as $k => $v)
                @php
                    $bd        = is_array($bdByBucket[$k] ?? null) ? $bdByBucket[$k] : null;
                    $formula   = $bd['formula'] ?? null;
                    $hasDetail = $bd !== null;
                @endphp
                <tr style="border-bottom: {{ $hasDetail ? 'none' : '1px solid rgba(15,20,17,0.08)' }};">
                    <td style="padding: 6px 12px 4px; font-size: 9px; color: #5A6259; width: 70%;">{{ $subBucketLabels[$k] ?? $k }}</td>
                    <td style="padding: 6px 12px 4px; font-size: 10px; font-weight: bold; color: #0F1411; text-align: right;">{{ $v }}</td>
                </tr>
                @if ($hasDetail)
                    @php
                        $rawInputs    = (array) ($bd['raw_inputs'] ?? []);
                        $tierTable    = (array) ($bd['tier_table'] ?? []);
                        $signals      = (array) ($bd['signals'] ?? []);
                        $suggestions  = (array) ($rawInputs['suggestions'] ?? []);
                        $llmReasoning = (string) ($bd['llm_reasoning'] ?? '');
                        $limitations  = (array) ($bd['limitations'] ?? []);
                        $signalLabels = [
                            'brand_recognition' => 'Pengenalan Brand',
                            'geographic_spread' => 'Sebaran Lokasi',
                            'variant_coverage'  => 'Variasi Pencarian',
                        ];

                        if ($formula === 'llm_judgment') {
                            $inputLine = implode(' · ', (array) ($rawInputs['context_provided'] ?? []));
                        } elseif ($formula === 'deterministic_signals') {
                            $inputLine = sprintf(
                                'brand_stem: %s · sumber: %s',
                                (string) ($rawInputs['brand_stem'] ?? '—'),
                                (string) ($rawInputs['source'] ?? 'Google Autocomplete'),
                            );
                        } else {
                            $parts = [];
                            foreach ($rawInputs as $rk => $rv) {
                                if (in_array($rk, ['source', 'suggestions', 'suggestion_count', 'brand_name', 'brand_stem', 'fetched_at'], true)) continue;
                                $parts[] = $rk . ': ' . (is_bool($rv) ? ($rv ? 'Ya' : 'Tidak') : $rv);
                            }
                            $inputLine = implode(' · ', $parts);
                        }
                    @endphp
                    <tr style="border-bottom: 1px solid rgba(15,20,17,0.08);">
                        <td colspan="2" style="padding: 6px 12px 8px; font-size: 8px; color: #5A6259; background: #F7F9F5;">
                            {{-- BB35: dropped the "▸ Cara Perhitungan" chevron-prefixed
                                 header — in PDF context the chevron looked like a
                                 collapsed-dropdown affordance even though the breakdown
                                 below already renders inline. The Sumber/Formula line
                                 below carries enough labelling on its own. Phase 9 will
                                 replace this entire breakdown with the apikprimadya
                                 table + ✓/✗ pattern. --}}

                            @php
                                $formulaLabel = match ($formula) {
                                    'deterministic_threshold' => 'Threshold tier-based (deterministik)',
                                    'deterministic_signals'   => 'Signal-based weighted (deterministik)',
                                    'llm_judgment'            => 'Penilaian LLM (Claude)',
                                    default                   => 'Lainnya',
                                };
                                $sourceLabel = match ($k) {
                                    'rating_tier', 'review_count_tier', 'keyword_saturation', 'review_keyword_quality', 'sentiment_quality' => 'Google Maps reviews',
                                    'search_recall' => 'Google Autocomplete',
                                    'has_gmaps', 'has_instagram', 'has_website', 'has_wa', 'has_tiktok' => 'Touchpoint input form',
                                    'review_bonus' => 'Google Maps review count threshold',
                                    'kehadiran_digital', 'konsistensi_visual', 'kelengkapan_layanan', 'transparansi_harga' => 'Penilaian visual + URL touchpoint',
                                    'base', 'bonus_ekspres', 'bonus_antar_jemput', 'bonus_variasi_layanan', 'bonus_sop_keluhan', 'bonus_price_list', 'penalty_keterlambatan', 'penalty_pakaian_hilang', 'penalty_no_response_wa' => 'Penilaian LLM dari konteks brand',
                                    default => 'Konteks brand',
                                };
                            @endphp
                            <p style="margin: 0 0 4px; line-height: 1.55; font-size: 8px;"><span style="font-weight: bold;">Sumber: </span>{{ $sourceLabel }} · <span style="font-weight: bold;">Formula: </span>{{ $formulaLabel }}</p>

                            @if ($k === 'search_recall')
                                <p style="margin: 0 0 4px; line-height: 1.55; color: #5A6259; font-size: 8px;">Frekuensi dan variasi brand muncul di hasil autocomplete pencarian.</p>
                            @endif

                            <span style="font-weight: bold;">Berdasarkan: </span>{{ $inputLine }}

                            @if ($formula === 'deterministic_threshold' && count($tierTable) > 0)
                                <table style="margin-top: 4px; font-size: 8px; border-collapse: collapse; width: auto;">
                                    @foreach ($tierTable as $tier)
                                        @php $isMatch = (bool) ($tier['matched'] ?? false); @endphp
                                        <tr style="background: {{ $isMatch ? '#3D8948' : 'transparent' }}; color: {{ $isMatch ? '#FFFFFF' : '#5A6259' }};">
                                            <td style="padding: 2px 10px 2px 0;">{{ $tier['range'] }}</td>
                                            <td style="padding: 2px 10px; text-align: right; font-weight: {{ $isMatch ? 'bold' : 'normal' }};">{{ $tier['points'] }} pt</td>
                                        </tr>
                                    @endforeach
                                </table>
                            @endif

                            @if ($formula === 'deterministic_signals' && count($signals) > 0)
                                <table style="margin-top: 4px; font-size: 8px; border-collapse: collapse; width: 100%;">
                                    @foreach ($signals as $sigKey => $sig)
                                        @php
                                            $sigScore  = (int) ($sig['score'] ?? 0);
                                            $sigCap    = (int) ($sig['cap'] ?? 0);
                                            $sigDetail = (string) ($sig['detail'] ?? '');
                                            $isFull    = $sigCap > 0 && $sigScore >= $sigCap;
                                        @endphp
                                        <tr style="background: {{ $isFull ? '#3D8948' : 'transparent' }}; color: {{ $isFull ? '#FFFFFF' : '#5A6259' }};">
                                            <td style="padding: 2px 10px 2px 0;">{{ $signalLabels[$sigKey] ?? $sigKey }}</td>
                                            <td style="padding: 2px 10px; text-align: right; font-weight: {{ $isFull ? 'bold' : 'normal' }}; white-space: nowrap;">{{ $sigScore }} / {{ $sigCap }} pt</td>
                                        </tr>
                                        @if ($sigDetail !== '')
                                            <tr>
                                                <td colspan="2" style="padding: 0 10px 2px 0; font-size: 7px; color: #8A9088; line-height: 1.5;">{{ $sigDetail }}</td>
                                            </tr>
                                        @endif
                                    @endforeach
                                </table>

                                @if (count($suggestions) > 0)
                                    <p style="margin: 4px 0 2px; font-weight: bold; font-size: 8px; color: #5A6259;">Top {{ count($suggestions) }} hasil autocomplete:</p>
                                    <ol style="margin: 0 0 4px 14px; padding: 0; font-size: 7px; color: #5A6259; line-height: 1.4;">
                                        @foreach ($suggestions as $sug)
                                            <li>{{ $sug }}</li>
                                        @endforeach
                                    </ol>
                                @endif
                            @endif

                            @if ($formula === 'llm_judgment' && $llmReasoning !== '')
                                <p style="margin: 4px 0 2px; line-height: 1.55; color: #0F1411; font-size: 8px;">{{ $llmReasoning }}</p>
                            @endif

                            @if (count($limitations) > 0)
                                <p style="margin: 3px 0 0; font-style: italic; color: #8A9088; font-size: 7px;">Keterbatasan: {{ implode('; ', $limitations) }}</p>
                            @endif
                        </td>
                    </tr>
                @endif
            @endforeach
        </table>
    @endif

    {{-- AI reasoning --}}
    @if ($reasoning !== '')
        <h3 style="font-size: 11px; color: #5A6259; margin-bottom: 6px;">Analisis</h3>
        <p style="font-size: 10px; color: #0F1411; line-height: 1.6; margin-bottom: 18px;">{{ $reasoning }}</p>
    @endif

    {{-- Evidence list --}}
    @if (count($evidence) > 0)
        <h3 style="font-size: 11px; color: #5A6259; margin-bottom: 6px;">Bukti Pengamatan</h3>
        @foreach ($evidence as $e)
            @php
                $impact   = is_array($e) ? ($e['impact'] ?? 'neutral') : 'neutral';
                $obs      = is_array($e) ? ($e['observation'] ?? '') : (string) $e;
                $tp       = is_array($e) ? ($e['touchpoint'] ?? null) : null;
                $borderClr = match ($impact) {
                    'positive' => '#3D8948',
                    'negative' => '#C24E3A',
                    default    => '#8A9088',
                };
                $bgClr = match ($impact) {
                    'positive' => '#E8F1E5',
                    'negative' => '#FBE6E1',
                    default    => '#F7F9F5',
                };
            @endphp
            <div style="border-left: 3px solid {{ $borderClr }}; background: {{ $bgClr }}; padding: 6px 10px; margin-bottom: 6px;">
                @if ($tp)
                    <p style="font-size: 8px; color: #8A9088; margin: 0 0 2px 0;">{{ $tp }}</p>
                @endif
                <p style="font-size: 9px; color: #0F1411; margin: 0; line-height: 1.55;">{{ $obs }}</p>
            </div>
        @endforeach
    @endif
@endforeach

{{-- ========================== RECOMMENDATIONS ========================== --}}
@if (count($recommends) > 0)
    <div style="page-break-before: always;"></div>
    <h2 style="font-size: 18px; color: #0F1411; margin-bottom: 4px;">Rekomendasi Prioritas</h2>
    <p style="font-size: 10px; color: #5A6259; margin-bottom: 18px;">Tindakan konkret yang bisa Anda mulai dari sekarang, diurutkan berdasarkan dampak.</p>

    @foreach ($recommends as $rec)
        @php
            $prio = $rec['priority'] ?? 'opsional';
            $prioClr = match ($prio) {
                'tinggi'  => '#C24E3A',
                'penting' => '#C97A1B',
                default   => '#5A6259',
            };
            $prioBg = match ($prio) {
                'tinggi'  => '#FBE6E1',
                'penting' => '#FEF3DC',
                default   => '#F7F9F5',
            };
            $prioLabel = match ($prio) {
                'tinggi'  => 'Prioritas Tinggi',
                'penting' => 'Penting',
                default   => 'Opsional',
            };
            $bucketLabel = $subBucketLabels[$rec['bucket'] ?? ''] ?? ($rec['bucket'] ?? '');
            $pillarSlug  = $bucketToPillar[$rec['bucket'] ?? ''] ?? null;
            $pillarLbl   = $pillarSlug ? ($pillarLabels[$pillarSlug] ?? $pillarSlug) : null;
        @endphp
        <div style="border: 1px solid rgba(15,20,17,0.08); border-radius: 8px; padding: 14px 16px; margin-bottom: 12px;">
            <table style="margin-bottom: 6px;">
                <tr>
                    <td>
                        <span style="font-size: 8px; font-weight: bold; color: {{ $prioClr }}; background: {{ $prioBg }}; padding: 2px 8px; border-radius: 10px; border: 1px solid {{ $prioClr }};">
                            {{ $prioLabel }}
                        </span>
                        @if ($pillarLbl)
                            <span style="font-size: 8px; color: #8A9088; margin-left: 6px;">{{ $pillarLbl }} · {{ $bucketLabel }}</span>
                        @endif
                    </td>
                    @if (isset($rec['gap']))
                        <td style="text-align: right;">
                            <span style="font-size: 8px; color: #8A9088;">Gap {{ $rec['gap'] }} pt</span>
                        </td>
                    @endif
                </tr>
            </table>
            <p style="font-size: 12px; font-weight: bold; color: #0F1411; margin: 0 0 4px 0;">{{ $rec['title'] ?? '' }}</p>
            <p style="font-size: 10px; color: #5A6259; margin: 0; line-height: 1.6;">{{ $rec['body'] ?? '' }}</p>
        </div>
    @endforeach
@endif

{{-- ========================== IG PROFILE AUDIT SECTION (Phase 7-C BB14) ========================== --}}
{{-- Gated to instagram_audit_status='done' inside the partial; renders
     nothing for skipped/failed states until BB16 adds the banner. --}}
@include('pdf._instagram-audit', ['audit' => $audit])

{{-- ========================== GMAPS REVIEWS SECTION (Phase 8 BB28) ========================== --}}
{{-- Gated to gmaps_reviews_status inside the partial; renders status
     banner for non-done states (incl. legacy_places_api_only sentinel
     from BB30) and full review table + penalty payload for done. --}}
@include('pdf._gmaps-reviews', ['audit' => $audit])

{{-- ========================== AUDIT REFERENCE FOOTER ========================== --}}
<div style="page-break-before: always;"></div>
<h3 style="font-size: 11px; color: #5A6259; margin-bottom: 6px;">Detail Audit</h3>
<table style="border: 1px solid rgba(15,20,17,0.08); margin-bottom: 18px;">
    <tr>
        <td style="padding: 6px 12px; font-size: 9px; color: #5A6259; width: 30%;">Audit ID</td>
        <td style="padding: 6px 12px; font-size: 9px; color: #0F1411; font-family: 'DejaVu Sans Mono', monospace;">{{ $audit->id }}</td>
    </tr>
    <tr>
        <td style="padding: 6px 12px; font-size: 9px; color: #5A6259;">Brand</td>
        <td style="padding: 6px 12px; font-size: 9px; color: #0F1411;">{{ $brandName }}</td>
    </tr>
    @if ($audit->city)
        <tr>
            <td style="padding: 6px 12px; font-size: 9px; color: #5A6259;">Kota</td>
            <td style="padding: 6px 12px; font-size: 9px; color: #0F1411;">{{ $audit->city }}</td>
        </tr>
    @endif
    @if ($audit->service_type)
        <tr>
            <td style="padding: 6px 12px; font-size: 9px; color: #5A6259;">Jenis Layanan</td>
            <td style="padding: 6px 12px; font-size: 9px; color: #0F1411;">{{ $audit->service_type }}</td>
        </tr>
    @endif
    <tr>
        <td style="padding: 6px 12px; font-size: 9px; color: #5A6259;">Tanggal Audit</td>
        <td style="padding: 6px 12px; font-size: 9px; color: #0F1411;">{{ optional($audit->created_at)->locale('id')->translatedFormat('d F Y') ?? $generatedAt }}</td>
    </tr>
    @php $audit_url = url('/audit/' . $audit->session_token); @endphp
    <tr>
        <td style="padding: 6px 12px; font-size: 9px; color: #5A6259;">URL Dashboard</td>
        <td style="padding: 6px 12px; font-size: 8px; color: #3D8948; font-family: 'DejaVu Sans Mono', monospace;">{{ $audit_url }}</td>
    </tr>
</table>

<p style="font-size: 8px; color: #8A9088; margin-top: 24px; text-align: center;">
    Dokumen ini dihasilkan secara otomatis oleh Nema Brand Health Check.<br/>
    Skor merefleksikan analisis pada {{ $generatedAt }} dan dapat berubah seiring perkembangan brand Anda.
</p>

</body>
</html>
