<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;

class KolExport implements
    FromArray,
    WithHeadings,
    WithTitle,
    WithStyles,
    WithColumnWidths,
    WithEvents
{
    protected array $kols;
    protected string $kota;
    protected string $niche;

    public function __construct(array $kols, string $kota = '', string $niche = '')
    {
        $this->kols  = $kols;
        $this->kota  = $kota;
        $this->niche = $niche;
    }

    public function title(): string
    {
        return 'KOL Report';
    }

    public function headings(): array
    {
        return [
            'No', 'Username', 'Full Name', 'Tier',
            'Followers', 'Following', 'Total Posts',
            'Avg Likes', 'Avg Comments', 'Engagement Rate (%)',
            'Bio', 'External URL', 'Verified',
            'Instagram URL', 'Posts Ditemukan',
        ];
    }

    public function array(): array
    {
        return collect($this->kols)->map(function ($kol, $index) {
            return [
                $index + 1,
                '@' . $kol['username'],
                $kol['fullName'] ?? '',
                $kol['tier'] ?? '',
                $kol['followers'] ?? 0,
                $kol['following'] ?? 0,
                $kol['posts'] ?? 0,
                $kol['avgLikes'] ?? 0,
                $kol['avgComments'] ?? 0,
                $kol['engagement'] ?? 0,
                $kol['bio'] ?? '',
                $kol['externalUrl'] ?? '',
                ($kol['isVerified'] ?? false) ? 'Ya' : 'Tidak',
                $kol['igUrl'] ?? '',
                $kol['postCount'] ?? 0,
            ];
        })->toArray();
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            1 => [
                'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF'], 'size' => 11],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '2E7D32']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            ],
        ];
    }

    public function columnWidths(): array
    {
        return [
            'A' => 5,  'B' => 22, 'C' => 25, 'D' => 10,
            'E' => 12, 'F' => 12, 'G' => 12, 'H' => 12,
            'I' => 14, 'J' => 18, 'K' => 40, 'L' => 30,
            'M' => 10, 'N' => 40, 'O' => 16,
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet   = $event->sheet->getDelegate();
                $lastRow = count($this->kols) + 1;

                $sheet->getRowDimension(1)->setRowHeight(25);
                $sheet->freezePane('A2');

                $sheet->getStyle("A1:O{$lastRow}")->applyFromArray([
                    'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'DDDDDD']]],
                ]);

                for ($row = 2; $row <= $lastRow; $row++) {
                    $color = ($row % 2 === 0) ? 'F1F8F1' : 'FFFFFF';
                    $sheet->getStyle("A{$row}:O{$row}")->applyFromArray([
                        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $color]],
                    ]);
                }

                for ($row = 2; $row <= $lastRow; $row++) {
                    $tier = $sheet->getCell("D{$row}")->getValue();
                    $tierColor = match ($tier) {
                        'Macro'   => 'FFF3CD',
                        'Mid'     => 'D4EDDA',
                        'Micro'   => 'CCE5FF',
                        'Nano'    => 'E2D9F3',
                        default   => 'FFFFFF',
                    };
                    $sheet->getStyle("D{$row}")->applyFromArray([
                        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $tierColor]],
                        'font' => ['bold' => true],
                    ]);
                }

                $sheet->insertNewRowBefore(1, 2);
                $sheet->setCellValue('A1', 'KOL Report — ' . strtoupper($this->kota) . ' · ' . strtoupper($this->niche));
                $sheet->setCellValue('A2', 'Generated by Chimera Creative · ' . now()->format('d M Y H:i'));
                $sheet->mergeCells('A1:O1');
                $sheet->mergeCells('A2:O2');
                $sheet->getStyle('A1')->applyFromArray([
                    'font' => ['bold' => true, 'size' => 13, 'color' => ['rgb' => '1B5E20']],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                ]);
                $sheet->getStyle('A2')->applyFromArray([
                    'font' => ['size' => 10, 'color' => ['rgb' => '888888'], 'italic' => true],
                    'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                ]);
            },
        ];
    }
}
