<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase 9 BB36: persist apikprimadya-quality LLM-generated artefacts
 * on the BrandAudit row. Each artefact is generated by its own
 * dedicated service (BB37) called from the Track A batch (BB38) after
 * pillar scoring + experience penalties land. The PDF redesign
 * (BB39-BB43) consumes them as the source-of-truth for each section.
 *
 * Column shapes:
 *
 *   recommendations: list of 5 ranked actions, apikprimadya structure
 *     [
 *       {
 *         rank: int 1-5,
 *         title: string,
 *         priority: 'TINGGI' | 'SEDANG' | 'RENDAH',
 *         effort:   'RENDAH' | 'SEDANG' | 'TINGGI',
 *         impact:   'RENDAH' | 'SEDANG' | 'TINGGI' | 'SANGAT TINGGI',
 *         description: string  // 2-3 sentence body
 *       },
 *       ...
 *     ]
 *
 *   quick_wins: list of 5-7 immediate-action items
 *     [
 *       { action: string, estimated_minutes: int },
 *       ...
 *     ]
 *
 *   competitive_positioning: { narrative: string, growth_opportunity: string }
 *     narrative is 1-2 paragraph competitive analysis;
 *     growth_opportunity is the single-sentence callout used in the
 *     "Peluang Pertumbuhan" highlighted box.
 *
 * All three are nullable until the Phase 9 generators run; existing
 * audits stay valid and the PDF templates fall back gracefully when
 * any column is null (BB44 covers backfill).
 */
return new class extends Migration {
    /**
     * Note: `recommendations` already exists from the original
     * create_brand_audits_table migration — same shape, just
     * pre-Phase-9 simpler structure. The BB37 RecommendationGenerator
     * overwrites it with the new apikprimadya-structured payload on
     * each audit, so no backfill needed; readers tolerate either
     * shape.
     */
    public function up(): void
    {
        Schema::table('brand_audits', function (Blueprint $table) {
            $table->json('quick_wins')->nullable()->after('recommendations');
            $table->json('competitive_positioning')->nullable()->after('quick_wins');
        });
    }

    public function down(): void
    {
        Schema::table('brand_audits', function (Blueprint $table) {
            $table->dropColumn(['quick_wins', 'competitive_positioning']);
        });
    }
};
